# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

source 'https://github.com/CocoaPods/Specs.git'

target "NTJsonModelStoreExample" do
    
    pod 'NTJsonStore', :git => 'https://github.com/NagelTech/NTJsonStore.git', :branch => 'develop'
    pod 'NTJsonModel', :git => 'https://github.com/NagelTech/NTJsonModel.git', :branch => 'develop'

end

